/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import javax.swing.ImageIcon;

/**
 *
 * @author Mario A
 */
public class PanelJugador extends javax.swing.JPanel {

    /**
     * Creates new form PanelJugador
     */
    public PanelJugador() {
        initComponents();
    }

    public void setDatos(String pFoto, String pNombre, String pPosicion, int pNumero, int pEdad, int pEstatura) {

        Lbl_Foto.setIcon(new ImageIcon(getClass().getResource(pFoto)));
        Lbl_Nombre.setText("Nombre: " + pNombre);
        Lbl_Puesto.setText(pPosicion);
        if (!pPosicion.equals("Entrenador")) 
        {
            Lbl_Numero.setText("Número: " + pNumero);
            Lbl_Edad.setText("Edad: " + pEdad + " años");
            Lbl_Estatura.setText("Estatura: " + pEstatura + " cm");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Foto = new javax.swing.JLabel();
        Lbl_Nombre = new javax.swing.JLabel();
        Lbl_Puesto = new javax.swing.JLabel();
        Lbl_Numero = new javax.swing.JLabel();
        Lbl_Edad = new javax.swing.JLabel();
        Lbl_Estatura = new javax.swing.JLabel();

        Lbl_Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Fuleco.jpg"))); // NOI18N

        Lbl_Nombre.setText("Nombre: Vicente Del Bosque");

        Lbl_Puesto.setText("Entrenador");

        Lbl_Numero.setText("Numero: 23");

        Lbl_Edad.setText("Edad: 67 años");

        Lbl_Estatura.setText("Estatura: 180 cm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Numero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_Puesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(Lbl_Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_Estatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Lbl_Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Puesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Edad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Estatura)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Edad;
    private javax.swing.JLabel Lbl_Estatura;
    private javax.swing.JLabel Lbl_Foto;
    private javax.swing.JLabel Lbl_Nombre;
    private javax.swing.JLabel Lbl_Numero;
    private javax.swing.JLabel Lbl_Puesto;
    // End of variables declaration//GEN-END:variables
}
