/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import javax.swing.ImageIcon;

/**
 *
 * @author Mario A
 */
public class PanelResultadoPartido extends javax.swing.JPanel {

    ImageIcon expandir = new ImageIcon(getClass().getResource("/Imagenes/expandir.png"));
    ImageIcon colapsar = new ImageIcon(getClass().getResource("/Imagenes/colapsar.png"));
    String marcador;

    /**
     * Creates new form PanelResultadoPartido
     */
    public PanelResultadoPartido() {
        initComponents();
        marcador = "5:1";
        Lbl_Expandir.setIcon(expandir);
        Pnl_Informacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_Versus = new javax.swing.JPanel();
        Lbl_BanderaVisita = new javax.swing.JLabel();
        Lbl_BanderaCasa = new javax.swing.JLabel();
        Lbl_EquipoCasa = new javax.swing.JLabel();
        Lbl_EquipoVisita = new javax.swing.JLabel();
        Lbl_FechaYHora = new javax.swing.JLabel();
        Lbl_VS = new javax.swing.JLabel();
        Lbl_Expandir = new javax.swing.JLabel();
        Pnl_Informacion = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        Pnl_Versus.setBackground(new java.awt.Color(245, 224, 200));

        Lbl_BanderaVisita.setBackground(new java.awt.Color(204, 0, 204));
        Lbl_BanderaVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBanderas/Inglaterra.png"))); // NOI18N
        Lbl_BanderaVisita.setOpaque(true);

        Lbl_BanderaCasa.setBackground(new java.awt.Color(204, 0, 204));
        Lbl_BanderaCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBanderas/Costa Rica.png"))); // NOI18N
        Lbl_BanderaCasa.setOpaque(true);

        Lbl_EquipoCasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_EquipoCasa.setText("Iran");

        Lbl_EquipoVisita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_EquipoVisita.setText("Argentina");

        Lbl_FechaYHora.setText("25 Junio 2014 - 10:00 AM");

        Lbl_VS.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        Lbl_VS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_VS.setText("vs");

        Lbl_Expandir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_ExpandirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pnl_VersusLayout = new javax.swing.GroupLayout(Pnl_Versus);
        Pnl_Versus.setLayout(Pnl_VersusLayout);
        Pnl_VersusLayout.setHorizontalGroup(
            Pnl_VersusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_VersusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_EquipoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_EquipoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Pnl_VersusLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Lbl_BanderaCasa)
                .addGap(27, 27, 27)
                .addComponent(Lbl_VS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(Lbl_BanderaVisita)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_VersusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_Expandir)
                .addContainerGap())
            .addGroup(Pnl_VersusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_FechaYHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Pnl_VersusLayout.setVerticalGroup(
            Pnl_VersusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_VersusLayout.createSequentialGroup()
                .addComponent(Lbl_FechaYHora, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(Pnl_VersusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_BanderaCasa)
                    .addComponent(Lbl_BanderaVisita)
                    .addComponent(Lbl_VS, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_VersusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_EquipoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_EquipoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(Lbl_Expandir)
                .addGap(5, 5, 5))
        );

        add(Pnl_Versus);

        Pnl_Informacion.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout Pnl_InformacionLayout = new javax.swing.GroupLayout(Pnl_Informacion);
        Pnl_Informacion.setLayout(Pnl_InformacionLayout);
        Pnl_InformacionLayout.setHorizontalGroup(
            Pnl_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        Pnl_InformacionLayout.setVerticalGroup(
            Pnl_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        add(Pnl_Informacion);
    }// </editor-fold>//GEN-END:initComponents

    private void Lbl_ExpandirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_ExpandirMouseClicked
        if (Lbl_Expandir.getIcon() == expandir) {
            Lbl_Expandir.setIcon(colapsar);
            Lbl_VS.setText(marcador);
        } else {
            Lbl_Expandir.setIcon(expandir);
            Lbl_VS.setText("vs");
        }
        Pnl_Informacion.setVisible(!Pnl_Informacion.isVisible());
    }//GEN-LAST:event_Lbl_ExpandirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_BanderaCasa;
    private javax.swing.JLabel Lbl_BanderaVisita;
    private javax.swing.JLabel Lbl_EquipoCasa;
    private javax.swing.JLabel Lbl_EquipoVisita;
    private javax.swing.JLabel Lbl_Expandir;
    private javax.swing.JLabel Lbl_FechaYHora;
    private javax.swing.JLabel Lbl_VS;
    private javax.swing.JPanel Pnl_Informacion;
    private javax.swing.JPanel Pnl_Versus;
    // End of variables declaration//GEN-END:variables
}
