/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfazGrafica;

import javax.swing.ImageIcon;

/**
 *
 * @author Mario A
 */
public class PanelEstadio extends javax.swing.JPanel {

    /**
     * Creates new form PanelEstadio
     */
    public PanelEstadio() {
        initComponents();
    }
    
    /**
     * Metodo para establecer los datos de un nuevo estadio y cargar la informacion
     * respectiva en el PanelEstadio
     * @param pNombreEstadio nombre del estadio
     * @param pCiudad ciudad donde se ubica el estadio
     * @param pCapacidad capacidad del estadio
     */
    public void setDatos(String pNombreEstadio, String pCiudad, int pCapacidad){
        // Se crea la ruta de la imagen del estadio
        String rutaImagen = "/ImagenesEstadios/"+pNombreEstadio+".jpg";
        // Se establece la imagen, el nombre, la ciudad y la capacidad del estadio.
        try{
            Lbl_Imagen.setIcon(new ImageIcon(getClass().getResource(rutaImagen)));
        }catch(Exception e){
            Lbl_Imagen.setIcon(new ImageIcon(getClass().getResource("/Imagenes/EstadioDefault.png")));
        }
        Lbl_NombreEstadio.setText("Estadio:  " + pNombreEstadio);
        Lbl_CiudadEstadio.setText("Ciudad:  " + pCiudad);
        Lbl_CapacidadEstadio.setText(pCapacidad + " Personas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Imagen = new javax.swing.JLabel();
        Lbl_CiudadEstadio = new javax.swing.JLabel();
        Lbl_NombreEstadio = new javax.swing.JLabel();
        Lbl_CapacidadEstadio = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Lbl_CiudadEstadio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        Lbl_CiudadEstadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Lbl_NombreEstadio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        Lbl_NombreEstadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Lbl_CapacidadEstadio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        Lbl_CapacidadEstadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Lbl_NombreEstadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_CiudadEstadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_CapacidadEstadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(Lbl_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_NombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_CiudadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_CapacidadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_CapacidadEstadio;
    private javax.swing.JLabel Lbl_CiudadEstadio;
    private javax.swing.JLabel Lbl_Imagen;
    private javax.swing.JLabel Lbl_NombreEstadio;
    // End of variables declaration//GEN-END:variables
}
