/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfazGrafica;

import Codigo.NodoJugador;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Mario A
 */
public class PanelGoleador extends javax.swing.JPanel {

    /**
     * Creates new form PanelGoleador
     */
    public PanelGoleador() {
        initComponents();
    }
    
    /**
     * Metodo utilizado para introducir los datos del goleador
     * @param pSeleccion Seleccion a la que pertenece el goleador
     * @param pNombreJugador Nombre del goleador
     * @param pGoles Cantidad de goles anotados
     */
    public void setGoleadores(String pSeleccion, String pNombreJugador, int pGoles){        
        Lbl_Bandera.setIcon(new ImageIcon(getClass().getResource("/ImagenesBanderas/"+pSeleccion+".png")));
        Lbl_NombreEquipo.setText(pSeleccion);
        Lbl_NombreGoleador.setText(pNombreJugador);
        Lbl_Goles.setText(pGoles+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Bandera = new javax.swing.JLabel();
        Lbl_NombreEquipo = new javax.swing.JLabel();
        Lbl_NombreGoleador = new javax.swing.JLabel();
        Lbl_Goles = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        Lbl_Bandera.setBackground(new java.awt.Color(255, 204, 51));
        Lbl_Bandera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Lbl_NombreEquipo.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        Lbl_NombreEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_NombreEquipo.setText("Bosnia Herzegovina");

        Lbl_NombreGoleador.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        Lbl_NombreGoleador.setText("Karim Benzema");

        Lbl_Goles.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        Lbl_Goles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Goles.setText("4 Goles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_NombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Lbl_Bandera, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_NombreGoleador, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lbl_Goles, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Bandera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_NombreEquipo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lbl_Goles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(Lbl_NombreGoleador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Bandera;
    private javax.swing.JLabel Lbl_Goles;
    private javax.swing.JLabel Lbl_NombreEquipo;
    private javax.swing.JLabel Lbl_NombreGoleador;
    // End of variables declaration//GEN-END:variables
}
