/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfazGrafica;

import javax.swing.ImageIcon;

/**
 *
 * @author Mario A
 */
public class VentanaJugadores extends javax.swing.JFrame {

    /**
     * Creates new form VentanaJugadores
     */
    public VentanaJugadores() {
        initComponents();
    }
    
    public void AgregarJugador(PanelJugador pJugadorNuevo){
        jPanel1.add(pJugadorNuevo);
        jPanel1.repaint();
        jPanel1.revalidate();
    }
    
    public void agregarBanderaYLogo(String pSeleccion){
        Lbl_TituloJugadores.setText("Selección Nacional de " + pSeleccion);
        Lbl_NombreEquipo.setText(pSeleccion);
        Lbl_Bandera.setIcon(new ImageIcon(getClass().getResource("/ImagenesBanderas/" + pSeleccion + ".png")));
        Lbl_LogoFederacion.setIcon(new ImageIcon(getClass().getResource("/ImagenesFederacion/" + pSeleccion + ".png")));
        jPanel1.repaint();
        jPanel1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_TituloJugadores = new javax.swing.JLabel();
        Lbl_Bandera = new javax.swing.JLabel();
        Lbl_NombreEquipo = new javax.swing.JLabel();
        Lbl_LogoFederacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Jugadores");
        setResizable(false);

        Lbl_TituloJugadores.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Lbl_TituloJugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_TituloJugadores.setText("Jugadores");

        Lbl_Bandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBanderas/Costa Rica.png"))); // NOI18N

        Lbl_NombreEquipo.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        Lbl_NombreEquipo.setText("Costa Rica");

        Lbl_LogoFederacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFederacion/Costa Rica.png"))); // NOI18N
        Lbl_LogoFederacion.setToolTipText("Federacion Costarricense de Futbol");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new java.awt.GridLayout(8, 3));
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_TituloJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(Lbl_Bandera)
                                .addGap(6, 6, 6)
                                .addComponent(Lbl_NombreEquipo)
                                .addGap(499, 499, 499)
                                .addComponent(Lbl_LogoFederacion)))
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Lbl_TituloJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Bandera, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_NombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_LogoFederacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Bandera;
    private javax.swing.JLabel Lbl_LogoFederacion;
    private javax.swing.JLabel Lbl_NombreEquipo;
    private javax.swing.JLabel Lbl_TituloJugadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
